### ISSUE TITLE
some question on zyl_test_5.txt

### ISSUE THREAD

**Issue by xuanzhiliu** [Maka314/COMP9021_Ass1_test#15]
<img width="453" alt="image" src="https://github.com/Maka314/COMP9021_Ass1_test/assets/104879600/422eb979-e97c-4412-bb1f-e5be7212c6ae">

hi maka
thank for your testset, it really helps me.
I find a wrong in zyl_test_5.txt
All of us are should be "knaves", not "knave"
thank you

**Comment by Maka314** [comment]
Thanks for pointing this out!
This issue has been fixed
